### ISSUE TITLE
bugs in preprocess()

### ISSUE THREAD

**Issue by ParadoxZW** [fjwCode/answer_helper#4]
Traceback (most recent call last):
  File "C:\Users\96473\Desktop\aotohelper\answer_helper\auto_answer.py", line 16, in <module>
    positions = preprocess()
  File "C:\Users\96473\Desktop\aotohelper\answer_helper\ulits.py", line 37, in preprocess
    pixel = pixels[500, top]
IndexError: image index out of range

**Comment by fujiawei-dev** [comment]
这个不是bug，根据自己的手机调整一下参数就行
